services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: datawarehouse_flu
    container_name: datawarehouse_flu
    ports:
      - 60119:8501
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data