[ui]
hideTopBar = true     # enable in production. false=listen for changes in the source code and trigger re-runs

#[client]
# toolbarMode = "viewer"
# showSidebarNavigation = false

[theme]
base="light"

[server]
headless = true