name: flu-codon-bias
channels:
  - bioconda
  - conda-forge
  - anaconda
  - conda
  - pytorch
  - defaults
dependencies:
  - jupyter>=1.1.1
  - matplotlib>=3.9.2
  - numpy>=2
  - pandas>=2
  - python=3.11
  - python-fastjsonschema   # == fastjsonschema in pip
  - scikit-learn>=1.5.1
  - inflect>=6.2.0
  - python-kaleido=0.2.1  # == kaleido in pip
  - plotly
  - pyarrow>=17.0.0
  - tqdm
  - cleverdict>=1.9.2
  - pathvalidate
  - flatdict>=4.0.1
  - openpyxl
  - sktime
  - xlsxwriter>=3.2.0
  - sqlalchemy>=2.0.37
  - pip
  - pip:
    - dagviz>=0.4.0
